In [ ]:
"""
1) Import modules
2) Load pd dataframe
3) View df statistics
    3.1 View head
    3.2 Describe 
    3.3 
4)
"""

In [1]:
# 1) import modules 
import pandas as pd
import numpy as np
import pandas_ta as ta
import matplotlib.pyplot as plt
import sys, os
from datetime import datetime

In [2]:
# 2) Load pd dataframe 
df = pd.read_csv("data/BITSTAMP_BTCUSD_DAY.csv")

In [20]:
# Set non-exponential notion
pd.options.display.float_format = '{:.5f}'.format

#pd.reset_option('^display.', silent=True)

In [21]:
# 3) View DF statistics
df.describe()

,Unix,Open,High,Low,Close,Volume BTC,Volume USD
count,2808.00000,2808.00000,2808.00000,2808.00000,2808.00000,2808.00000,2808.00000
mean,1538395200.00000,12825.50386,13193.10217,12399.73010,12833.50089,12556904.20353,61699923.93076
std,70048290.46993,16618.15271,17078.50425,16069.51245,16617.96392,45917791.84428,105257248.21022
min,1417132800.00000,162.00000,212.84000,152.40000,162.00000,0.00000,0.00000
25%,1477764000.00000,702.92750,714.00000,691.06750,703.47250,4606.92471,10114.39500
50%,1538395200.00000,6769.97000,6970.25500,6599.27500,6773.44500,12167.94066,27471669.97652
75%,1599026400.00000,11976.49500,12552.72000,11650.50250,12012.31000,3112223.84250,81184761.05326
max,1659657600.00000,67547.49000,69000.00000,66250.00000,67559.00000,772329454.80000,1446125474.07654

In [22]:
df.head()

,Unix,Date,Symbol,Open,High,Low,Close,Volume BTC,Volume USD
0,1659657600,2022-08-05 00:00:00,BTC/USD,22630.14000,22690.50000,22587.94000,22667.14000,15.41781,349477.72826
1,1659571200,2022-08-04 00:00:00,BTC/USD,22830.37000,23228.77000,22400.00000,22615.24000,1537.96630,34781476.88351
2,1659484800,2022-08-03 00:00:00,BTC/USD,22997.07000,23642.14000,22686.12000,22835.88000,1306.29502,29830396.39097
3,1659398400,2022-08-02 00:00:00,BTC/USD,23291.67000,23468.33000,22665.98000,23001.52000,1441.50642,33156838.71940
4,1659312000,2022-08-01 00:00:00,BTC/USD,23287.38000,23511.50000,22861.00000,23282.92000,1310.17181,30504625.32254